<x-admin.modal id="global-date-modal" title="Pilih Tanggal" maxWidth="max-w-xs" zIndex="z-70">
    <div class="flex flex-col select-none relative">
        <!-- Calendar Header -->
        <div class="flex items-center justify-between mb-3 pb-3 border-b border-slate-100">
            <button type="button" id="cdm-prev-month" class="p-1.5 text-slate-500 hover:text-[#028DA9] hover:bg-slate-100 rounded-xl transition-colors cursor-pointer" title="Bulan Sebelumnya">
                <i data-feather="chevron-left" class="w-4 h-4"></i>
            </button>
            
            <div class="flex items-center gap-1.5">
                <!-- Custom Month Dropdown -->
                <div class="relative" id="cdm-month-dropdown">
                    <button
                        type="button"
                        id="cdm-month-btn"
                        class="flex items-center gap-1.5 text-xs font-bold text-slate-800 bg-slate-50 hover:bg-slate-100 hover:text-[#028DA9] border border-slate-200/80 rounded-xl py-1.5 px-2.5 transition-all duration-150 cursor-pointer active:scale-95 shadow-2xs"
                        aria-expanded="false"
                    >
                        <span id="cdm-month-label">September</span>
                        <i data-feather="chevron-down" id="cdm-month-chevron" class="w-3.5 h-3.5 text-slate-400 transition-transform duration-200"></i>
                    </button>

                    <!-- Month Menu Popover -->
                    <div
                        id="cdm-month-menu"
                        class="hidden absolute left-0 top-full mt-1.5 z-50 w-44 rounded-2xl bg-white p-1.5 shadow-2xl border border-slate-200/90 ring-1 ring-slate-900/5 max-h-52 overflow-y-auto scrollbar-thin"
                    >
                        <!-- Generated by JS -->
                    </div>
                </div>

                <!-- Custom Year Dropdown -->
                <div class="relative" id="cdm-year-dropdown">
                    <button
                        type="button"
                        id="cdm-year-btn"
                        class="flex items-center gap-1.5 text-xs font-bold text-slate-800 bg-slate-50 hover:bg-slate-100 hover:text-[#028DA9] border border-slate-200/80 rounded-xl py-1.5 px-2.5 transition-all duration-150 cursor-pointer active:scale-95 shadow-2xs"
                        aria-expanded="false"
                    >
                        <span id="cdm-year-label">2026</span>
                        <i data-feather="chevron-down" id="cdm-year-chevron" class="w-3.5 h-3.5 text-slate-400 transition-transform duration-200"></i>
                    </button>

                    <!-- Year Menu Popover -->
                    <div
                        id="cdm-year-menu"
                        class="hidden absolute right-0 top-full mt-1.5 z-50 w-32 rounded-2xl bg-white p-1.5 shadow-2xl border border-slate-200/90 ring-1 ring-slate-900/5 max-h-52 overflow-y-auto scrollbar-thin grid grid-cols-1 gap-0.5"
                    >
                        <!-- Generated by JS -->
                    </div>
                </div>
            </div>

            <button type="button" id="cdm-next-month" class="p-1.5 text-slate-500 hover:text-[#028DA9] hover:bg-slate-100 rounded-xl transition-colors cursor-pointer" title="Bulan Berikutnya">
                <i data-feather="chevron-right" class="w-4 h-4"></i>
            </button>
        </div>
        
        <!-- Days of week -->
        <div class="grid grid-cols-7 gap-1 mb-2 text-center text-[10px] font-bold uppercase tracking-wider text-slate-400">
            <div class="text-rose-500">Min</div>
            <div>Sen</div>
            <div>Sel</div>
            <div>Rab</div>
            <div>Kam</div>
            <div>Jum</div>
            <div class="text-emerald-600">Sab</div>
        </div>
        
        <!-- Calendar Grid -->
        <div id="cdm-grid" class="grid grid-cols-7 gap-1 text-center text-xs">
            <!-- Days will be generated by JS -->
        </div>

        <!-- Footer Actions -->
        <div class="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between">
            <button type="button" id="cdm-clear-btn" class="text-xs font-medium text-slate-400 hover:text-rose-600 cursor-pointer transition-colors px-2 py-1 rounded-lg hover:bg-rose-50">
                Kosongkan
            </button>
            <button type="button" id="cdm-today-btn" class="text-xs font-semibold text-[#028DA9] hover:text-[#016f86] cursor-pointer transition-colors px-2 py-1 rounded-lg hover:bg-[#028DA9]/10">
                Pilih Hari Ini
            </button>
        </div>
    </div>
</x-admin.modal>
